language: python
python:
  - "2.7"

# Add Ubuntu GIS repository
before_install:
  - "sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable"
  - "echo Yes"
  - "sudo apt-get update"
  - "sudo apt-get install libgdal-dev gdal-bin"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: nosetests
